#!/usr/bin/env bash
#
# Builds a signed release APK you can attach to an email.
#
#   ./scripts/release-apk.sh
#
# On the first run this generates a keystore in credentials/ and prints the
# details. Keep that folder — losing it means the next APK is signed with a
# different key and cannot upgrade an installed one. It is gitignored, so it
# never leaves this machine.
#
# The build is the state-switcher build: EXPO_PUBLIC_DEMO_PANEL=1 leaves the
# long-press panel in, because a reviewer needs to reach the edge states.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

CRED_DIR="$ROOT/credentials"
KEYSTORE="$CRED_DIR/skillio-release.keystore"
ENV_FILE="$CRED_DIR/keystore.env"

ALIAS="skillio"
OUT_DIR="$ROOT/build"

# --- keystore -----------------------------------------------------------------

if [[ ! -f "$KEYSTORE" ]]; then
  echo "==> No keystore yet — generating one."
  mkdir -p "$CRED_DIR"

  # Generated rather than prompted, so the build is repeatable and nothing has
  # to be typed twice. Rotate it by deleting credentials/ and running again.
  STORE_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"

  keytool -genkeypair -v \
    -keystore "$KEYSTORE" \
    -alias "$ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "$STORE_PASSWORD" \
    -keypass "$STORE_PASSWORD" \
    -dname "CN=Skillio, OU=Mobile, O=Skillio, L=, ST=, C=IN" >/dev/null

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/release-apk.sh — keep this, do not commit it.
SKILLIO_STORE_FILE=$KEYSTORE
SKILLIO_STORE_PASSWORD=$STORE_PASSWORD
SKILLIO_KEY_ALIAS=$ALIAS
SKILLIO_KEY_PASSWORD=$STORE_PASSWORD
EOF
  chmod 600 "$ENV_FILE" "$KEYSTORE"

  echo "==> Keystore written to credentials/ (alias: $ALIAS)."
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# --- native project -----------------------------------------------------------

# android/ is generated. Regenerate it so the signing plugin is applied, and so
# a stale folder from an older SDK can't quietly produce a broken build.
echo "==> Prebuilding android/"
npx expo prebuild --platform android --clean

# --- bundle + build -----------------------------------------------------------

echo "==> Assembling release APK"
export EXPO_PUBLIC_DEMO_PANEL=1

cd "$ROOT/android"
./gradlew --no-daemon assembleRelease \
  -PSKILLIO_STORE_FILE="$SKILLIO_STORE_FILE" \
  -PSKILLIO_STORE_PASSWORD="$SKILLIO_STORE_PASSWORD" \
  -PSKILLIO_KEY_ALIAS="$SKILLIO_KEY_ALIAS" \
  -PSKILLIO_KEY_PASSWORD="$SKILLIO_KEY_PASSWORD"

# --- collect ------------------------------------------------------------------

APK="$ROOT/android/app/build/outputs/apk/release/app-release.apk"
[[ -f "$APK" ]] || { echo "Build finished but $APK is missing." >&2; exit 1; }

VERSION="$(node -p "require('$ROOT/app.json').expo.version")"
mkdir -p "$OUT_DIR"
DEST="$OUT_DIR/skillio-$VERSION.apk"
cp "$APK" "$DEST"

echo
echo "==> $DEST"
echo "    $(du -h "$DEST" | cut -f1)"
echo
echo "Signed with credentials/skillio-release.keystore."
echo "Long-press the Home avatar for the state switcher."
